-- MySQL Script generated by MySQL Workbench
-- Fri Sep 18 09:48:28 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_academico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_academico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_academico` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_academico` ;

-- -----------------------------------------------------
-- Table `db_academico`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_academico`.`aluno` (
  `CO_ALUNO` INT NOT NULL,
  `DT_NASCIMENTO` DATETIME NULL DEFAULT NULL,
  `SG_SEXO` CHAR(1) NULL DEFAULT NULL,
  `NOME` VARCHAR(20) NULL DEFAULT NULL,
  `CO_ESTADOCIVIL` CHAR(1) NULL DEFAULT NULL,
  `NO_PAI` VARCHAR(70) NULL DEFAULT NULL,
  `NO_MAE` VARCHAR(70) NULL DEFAULT NULL,
  PRIMARY KEY (`CO_ALUNO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_academico`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_academico`.`curso` (
  `CO_CURSO` INT NOT NULL,
  `nome` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`CO_CURSO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_academico`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_academico`.`turma` (
  `CO_TURMA` CHAR(11) NOT NULL,
  `ANO` CHAR(4) NULL DEFAULT NULL,
  `PERIODO` CHAR(1) NULL DEFAULT NULL,
  `DESCRIÇÃO` CHAR(50) NULL DEFAULT NULL,
  `DT_INICIAL` DATETIME NULL DEFAULT NULL,
  `DT_FINAL` DATETIME NULL DEFAULT NULL,
  `NUM_PROVAS` INT NULL DEFAULT NULL,
  `CO_CURSO` INT NULL DEFAULT NULL,
  PRIMARY KEY (`CO_TURMA`),
  INDEX `FK_TURMA_CURSO` (`CO_CURSO` ASC) VISIBLE,
  CONSTRAINT `FK_TURMA_CURSO`
    FOREIGN KEY (`CO_CURSO`)
    REFERENCES `db_academico`.`curso` (`CO_CURSO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_academico`.`aluno_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_academico`.`aluno_turma` (
  `CO_ALUNO` INT NOT NULL,
  `CO_TURMA` CHAR(11) NOT NULL,
  `DT_MATRICULA` DATETIME NULL DEFAULT NULL,
  `DT_CANCELAMENTO` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`CO_ALUNO`, `CO_TURMA`),
  INDEX `FK_TURMA` (`CO_TURMA` ASC) VISIBLE,
  CONSTRAINT `FK_ALUNO`
    FOREIGN KEY (`CO_ALUNO`)
    REFERENCES `db_academico`.`aluno` (`CO_ALUNO`),
  CONSTRAINT `FK_TURMA`
    FOREIGN KEY (`CO_TURMA`)
    REFERENCES `db_academico`.`turma` (`CO_TURMA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_academico`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_academico`.`disciplina` (
  `CO_DISCIPLINA` CHAR(2) NOT NULL,
  `NO_DISCIPLINA` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`CO_DISCIPLINA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_academico`.`prova`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_academico`.`prova` (
  `CO_PROVA` CHAR(3) NOT NULL,
  `DS_PROVA` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`CO_PROVA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_academico`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_academico`.`avaliacao` (
  `CO_ALUNO` INT NOT NULL,
  `CO_TURMA` CHAR(11) NOT NULL,
  `CO_DISCIPLINA` CHAR(2) NOT NULL,
  `CO_PROVA` CHAR(3) NOT NULL,
  `DT_AVALIACAO` DATETIME NULL DEFAULT NULL,
  `NT_AVALIACAO` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`CO_TURMA`),
  INDEX `FK_DISCIPLINA` (`CO_DISCIPLINA` ASC) VISIBLE,
  INDEX `FK_PROVA` (`CO_PROVA` ASC) VISIBLE,
  CONSTRAINT `FK_ALUNO_TURMA_ALUNO`
    FOREIGN KEY (`CO_ALUNO`)
    REFERENCES `db_academico`.`aluno_turma` (`CO_ALUNO`),
  CONSTRAINT `FK_ALUNO_TURMA_TURMA`
    FOREIGN KEY (`CO_TURMA`)
    REFERENCES `db_academico`.`aluno_turma` (`CO_TURMA`),
  CONSTRAINT `FK_DISCIPLINA`
    FOREIGN KEY (`CO_DISCIPLINA`)
    REFERENCES `db_academico`.`disciplina` (`CO_DISCIPLINA`),
  CONSTRAINT `FK_PROVA`
    FOREIGN KEY (`CO_PROVA`)
    REFERENCES `db_academico`.`prova` (`CO_PROVA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_academico`.`frequencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_academico`.`frequencia` (
  `CO_ALUNO` INT NOT NULL,
  `CO_TURMA` CHAR(11) NOT NULL,
  `CO_DISCIPLINA` CHAR(2) NOT NULL,
  `DT_FREQUENCIA` DATETIME NOT NULL,
  `FREQUENCIA` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`CO_ALUNO`, `CO_TURMA`, `CO_DISCIPLINA`, `DT_FREQUENCIA`),
  INDEX `FK_TURMA_FREQUENCIA` (`CO_TURMA` ASC) VISIBLE,
  INDEX `FK_DISCIPLINA_FREQUENCIA` (`CO_DISCIPLINA` ASC) VISIBLE,
  CONSTRAINT `FK_ALUNO_FREQUENCIA`
    FOREIGN KEY (`CO_ALUNO`)
    REFERENCES `db_academico`.`aluno_turma` (`CO_ALUNO`),
  CONSTRAINT `FK_DISCIPLINA_FREQUENCIA`
    FOREIGN KEY (`CO_DISCIPLINA`)
    REFERENCES `db_academico`.`disciplina` (`CO_DISCIPLINA`),
  CONSTRAINT `FK_TURMA_FREQUENCIA`
    FOREIGN KEY (`CO_TURMA`)
    REFERENCES `db_academico`.`aluno_turma` (`CO_TURMA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_academico`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_academico`.`professor` (
  `CO_PROFESSOR` INT NOT NULL,
  `SG_SEXO` CHAR(1) NULL DEFAULT NULL,
  `NOME` VARCHAR(20) NULL DEFAULT NULL,
  `DT_NASCIMENTO` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`CO_PROFESSOR`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_academico`.`prof_turm_disc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_academico`.`prof_turm_disc` (
  `CO_PROFESSOR` INT NOT NULL,
  `CO_TURMA` CHAR(11) NOT NULL,
  `CO_DISCIPLINA` CHAR(2) NOT NULL,
  PRIMARY KEY (`CO_PROFESSOR`, `CO_TURMA`, `CO_DISCIPLINA`),
  INDEX `FK_TURMA_PROFESSOR` (`CO_TURMA` ASC) VISIBLE,
  INDEX `FK_DISCIPLINA_PROFESSOR` (`CO_DISCIPLINA` ASC) VISIBLE,
  CONSTRAINT `FK_DISCIPLINA_PROFESSOR`
    FOREIGN KEY (`CO_DISCIPLINA`)
    REFERENCES `db_academico`.`disciplina` (`CO_DISCIPLINA`),
  CONSTRAINT `FK_PROFESSOR`
    FOREIGN KEY (`CO_PROFESSOR`)
    REFERENCES `db_academico`.`professor` (`CO_PROFESSOR`),
  CONSTRAINT `FK_TURMA_PROFESSOR`
    FOREIGN KEY (`CO_TURMA`)
    REFERENCES `db_academico`.`turma` (`CO_TURMA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
