-- praticando SQL/DML - Data Manipulation Language
-- Comandos e consulta
select * -- qual(is) colunas a consultar
from db_academico.aluno;-- qual(is) tabelas de dados 

select CO_ALUNO as MATRICULA_ALUNO,
	NOME as 'NOME COMPLETO DO ALUNO'
from db_academico.ALUNO as TAB_ALUNO
where TAB_ALUNO.nome = 'MARIO ANDRADE';


-- vamosm consultar a tabela ALUNO,
-- ordenada pelo nome do aluno alfabeticamente
select AL.CO_ALUNO,
AL.NOME,
AL.SG_SEXO,
AL.CO_ESTADOCIVIL
from ALUNO AS AL
-- ORDER BY AL.NOME ASC; -- CLASSIFICA DE FORMA ASSENDENTE PELA COLUNA NOME
ORDER BY 2 DESC; -- TAMBEM POSSO CLASSIFICAR PELO GRAU(NRO) DA COLUNA DECRESCENTEMENTE

select AL.CO_ALUNO AS 'MATRICULA ALUNO',
AL.NOME AS 'NOME COMPLETO',
AL.SG_SEXO AS 'SIGLA SEXO',
AL.CO_ESTADOCIVIL AS 'ESTADO CIVIL',
(2*5) AS 'NOTA PARA TODOS OS ALUNOS' -- TAMBEM É POSSIVEL INCLUIR CALCULOS NA CONSULTA
from ALUNO AS AL
-- ORDER BY AL.NOME ASC; -- CLASSIFICA DE FORMA ASSENDENTE PELA COLUNA NOME
ORDER BY 2 DESC;

-- CONSULTANDO DADOS DE DUAS TABELAS
-- APRESENTANDO O CÓDIGO DO CURSO E NOME RELACIONADO COM CÓDIGO DA TURMA,
-- SEU ANO E NOME(DESCRICAO)
-- COM JUNÇÃO INPLICITA DE FORMA NATIVA

SELECT CURSO.CO_CURSO AS 'CÓDIGO DO CURSO',
CURSO.NOME AS 'NOME DO CURSO',
TURMA.CO_TURMA AS 'CÓDIGO DA TURMA',
TURMA.DESCRICAO AS 'NOME DA TURMA',
TURMA.ANO AS 'ANO DE INÍCIO DA TURMA'

 FROM CURSO INNER JOIN TURMA ON (CURSO.CO_CURSO = TURMA.CO_CURSO); -- JUNÇÃO IMPLÍCITA

SELECT CURSO.CO_CURSO AS 'CÓDIGO DO CURSO',
CURSO.NOME AS 'NOME DO CURSO',
TURMA.CO_TURMA AS 'CÓDIGO DA TURMA',
TURMA.DESCRICAO AS 'NOME DA TURMA',
TURMA.ANO AS 'ANO DE INÍCIO DA TURMA'
FROM CURSO, TURMA
WHERE CURSO.CO_CURSO = TURMA.CO_CURSO;


SELECT * FROM CURSO;
SELECT * FROM TURMA;

-- SE QUISERMOS SABER QUANTAS TURMAS EXISTEM NA TABELA TURMA
-- PODEMOS USAR UMA FUNÇÃO AGREGADA
SELECT COUNT(*) AS 'QUANTIDADE DE TURMAS'
FROM TURMA;

-- PARA EVITAR A CONTAGEM DE LINHAS DUPLICADAS
SELECT COUNT(DESCRICAO) AS ' QUANTIDADE DE TURMAS'
FROM TURMA AS TU
WHERE TU.DESCRICAO LIKE ' TURMA 01';

-- EXCLUINDO TUPLAS (LINHAS)DUPLICADAS
SELECT COUNT( DISTINCT DESCRICAO) AS 'QUANTIDADE DE TURMAS'
FROM TURMA AS TU;

-- VERIFICANDO A MAIOR E MENOR NOTA DA TABELA AVALIAÇÃO
SELECT MIN(AV.NT_AVALIACAO)
FROM AVALIACAO AS AV;

SELECT MAX(AV.NT_AVALIACAO)
FROM AVALIACAO AS AV;

-- VERIFICANDO A MÉDIA ARITMETICA SIMPLES DA TABELA AVALIACAO
SELECT SUM(AV.NT_AVALIACAO)/ COUNT(AV.NT_AVALIACAO) AS 'MÉDIA DE NOTAS'
FROM AVALIACAO AS AV;

-- POSSO TAMBEM USAR O METODO AVG (AVAREGE) DA MÉDIA ARITMETICA SIMPLES DA TABELA 
SELECT AVG(AV.NT_AVALIACAO) AS 'MÉDIA DE NOTAS'
FROM AVALIACAO AS AV;

-- SE QUISERMOS CONSULTAR POR MASCARA(OU SEJA, PARTE DO NOME)
-- MASCARA % (PERCENTUAL) PARA QUAISQUER CARACTERES
-- MASCARA _ (UNDERLINE) PARA UM CARACTER QUALQUER
SELECT *
 FROM ALUNO
 where nome like '%RO'; -- NOMES DE ALUNOS QUE TERMINAM COM RO 
 
SELECT *
 FROM ALUNO
 where nome like '_______';-- PARA NOME QUE POSSUEM 7 CARACTERES QUAISQUER
 
 SELECT *
 FROM ALUNO
 where nome like '%C__D%'; -- PARA QUAISQUER CARACTERES ANTES DA LETRA C 
 